config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'welcome#index'
  resources :owners
  resources :cards
    get "owners/:id/cards", to: 'cards#owners_by_card'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :owners
end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
   def index
    @cards = Card.all
  end
   def owners_by_card 
    @cards = Card.find(params[:id])
    # render json: @cards.owners
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all
  end

  def show 
    @owner = Owner.find(params[:id])
  end
# ////////////////////////////////////////////////////////////////

      def new
        @owner = Owner.new
      end
     
       def create 
        @owner = Owner.new(owner_params)
          if @owner.save
            redirect_to @owner
          else
            render :action => :new
          end
       end

# //////////////////////////////////////////////////////////////////////////

     def edit
      @owner = Owner.find(params[:id])
      end

      def update
      @owner = Owner.find(params[:id])

       if @owner.update(owner_params)
        redirect_to @owner
         else
          render :action => :edit
        end
      end


# /////////////////////////////////////////////////////////////////////////////

def destroy
@owner = Owner.find(params[:id])
@owner.destroy
redirect_to owners_url
end





#////////////////////////////////////////////////////
      private
      def owner_params
        params.require(:owner).permit(:name, :age, :level, :card_id)
      end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/views/cards/index.html.erb
<div class="cards">
     
   <h1>All the cards</h1>
    <% @cards.each do |card| %>
    <p><span>NAME: </span> <%= card[:name] %></p>
    <p> <span>POWER: </span> <%= card[:power] %></p>
    <p> <span>WEIGHT: </span><%= card[:weight] %></p> 
     <p><img src="<%=  card[:img_url] %>" alt=""></p>

    <% end -%>
<%= link_to "Go back to All players",owners_path %>
</div>

app/views/cards/owners_by_card.html.erb
<div class="card">
  
  <h1>Your Cards</h1>
  <p>Name: <%= @cards[:name] %></p>
   <p> Power: <%= @cards[:power] %></p>
 <p><img src="<%= @cards[:img_url] %>" alt=""></p>
 <p>Weight: <%= @cards[:weight] %></p>
 <%= link_to "Go back to All players",owners_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToysCards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/owners/_form.html.erb
<div class="form">
  
 <p><%= form_for @owner do |form| %></p>
 <p>Name: <%= form.text_field :name %></br></p>
<p>Age:  <%= form.text_field :age %></br></p>
<p>Status: <%= form.text_field :level %></br></p>
<p>Picture:  <%= form.text_field :img_url %></br></p>
<p>Choose a random card <%= form.text_field :card_id %></br></p>

  <p><%= form.submit %></p>
<% end -%>
</div>

app/views/owners/edit.html.erb
<center><div class="edit">
   
<h1>Edit trainer</h1>
 <%= render :partial => 'form' %>


</div></center>

app/views/owners/index.html.erb
<div class="index">
    <center><h1>All Contenders</h1></center>
    <div class="info">
        <% @owners.each do |owner| %>
            <p class="name">
              Name: <%= link_to owner[:name], owner_path(owner) %>
          <img src="<%= owner[:img_url] %>" alt="">
           <%=link_to "Edit trainer", edit_owner_path(owner) %>
           

            </p>
            <!-- <p class="profile_pic"><img src="<%= owner[:img_url] %>" alt=""> </p>  -->
            <p class="edit_link">
<!--                 <%=link_to "Edit trainer", edit_owner_path(owner) %>
 -->            </p>
            <p >
           <%= button_to "Delete this trainer", owner, :method => :delete, data:{ confirm: "Are you sure you want to delete this trainer?" } %> </p>
                <% end %>
    </div>
<!--     <%= link_to "Create a owner", new_owner_path %>
 --></div>
    <p class="new"> <%= link_to "Create a Contender", new_owner_path %></p>
        <p class="new"> <%= link_to "See Avalaible Cards", cards_path %></p>

app/views/owners/new.html.erb
<center>
  
<div>
  <h1>Create a new Owner</h1>
  <%= render :partial => 'form' %>
</div>

</center>

app/views/owners/show.html.erb
<div class="show">

<h1>Here's the information Mr/Mrs <%= @owner[:name] %> </h1>
  <p>Name: <%= @owner[:name] %></p>
  <p> AGE: <%= @owner[:age] %></p>
<p> STATUS: <%= @owner[:level] %></p>
<p> card: <%= @owner[:card_id] %></p>


<%= link_to('Your Toys Cards Collection', "/owners/#{@owner.card_id}/cards") %>
</div>